/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TabPrismPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  rules: [],
  syncFileExplorer: false,
  fileExplorerStyle: "text",
  pinnedTabStyle: "full"
};
var COLOR_PRESETS = [
  { name: "Red", hex: "#ef5350" },
  { name: "Orange", hex: "#ffa726" },
  { name: "Yellow", hex: "#ffee58" },
  { name: "Green", hex: "#66bb6a" },
  { name: "Teal", hex: "#26a69a" },
  { name: "Blue", hex: "#42a5f5" },
  { name: "Indigo", hex: "#5c6bc0" },
  { name: "Purple", hex: "#ab47bc" },
  { name: "Pink", hex: "#ec407a" }
];

// src/styleGenerator.ts
function hexToRgb(hex) {
  let cleanHex = hex.replace(/^#/, "").trim();
  if (cleanHex.length === 3) {
    cleanHex = cleanHex.split("").map((c) => c + c).join("");
  }
  const num = parseInt(cleanHex, 16);
  if (isNaN(num) || cleanHex.length !== 6) {
    return { r: 100, g: 100, b: 100 };
  }
  return {
    r: num >> 16 & 255,
    g: num >> 8 & 255,
    b: num & 255
  };
}
function generateDynamicCSS(settings) {
  let css = "";
  settings.rules.forEach((rule) => {
    if (rule.enabled === false)
      return;
    const { r, g, b } = hexToRgb(rule.color);
    const bgActive = `rgba(${r}, ${g}, ${b}, ${rule.activeOpacity})`;
    const bgInactive = `rgba(${r}, ${g}, ${b}, ${rule.inactiveOpacity})`;
    css += `
      /* Rule variables for: ${rule.folderPath} */
      .workspace-tab-header[data-tabprism-rule="${rule.id}"] {
        --tab-folder-accent: ${rule.color};
        --tab-folder-bg-active: ${bgActive};
        --tab-folder-bg-inactive: ${bgInactive};
      }

      /* Target element overrides */
      .workspace-tab-header[data-tabprism-rule="${rule.id}"][data-style-bg="true"].is-active,
      .workspace-tab-header[data-tabprism-rule="${rule.id}"][data-style-bg="true"].mod-active {
        background-color: var(--tab-folder-bg-active) !important;
      }
      .workspace-tab-header[data-tabprism-rule="${rule.id}"][data-style-bg="true"]:not(.is-active):not(.mod-active) {
        background-color: var(--tab-folder-bg-inactive) !important;
      }
      .workspace-tab-header[data-tabprism-rule="${rule.id}"][data-style-bg="true"] .workspace-tab-header-inner {
        background-color: transparent !important;
      }

      .workspace-tab-header[data-tabprism-rule="${rule.id}"][data-style-border="true"].is-active,
      .workspace-tab-header[data-tabprism-rule="${rule.id}"][data-style-border="true"].mod-active {
        border-top: 2px solid var(--tab-folder-accent) !important;
      }
      .workspace-tab-header[data-tabprism-rule="${rule.id}"][data-style-border="true"]:not(.is-active):not(.mod-active) {
        border-top: 1px solid ${bgInactive} !important;
      }

      .workspace-tab-header[data-tabprism-rule="${rule.id}"][data-style-text="true"] .workspace-tab-header-inner-title {
        color: ${rule.customTextColorEnabled ? rule.customTextColor : "var(--tab-folder-accent)"} !important;
      }

      .workspace-tab-header[data-tabprism-rule="${rule.id}"][data-style-icons="true"] .workspace-tab-header-inner-icon,
      .workspace-tab-header[data-tabprism-rule="${rule.id}"][data-style-icons="true"] .workspace-tab-header-status-container {
        color: ${rule.customTextColorEnabled ? rule.customTextColor : "var(--tab-folder-accent)"} !important;
      }
    `;
    if (settings.syncFileExplorer) {
      const applyTextColor = rule.applyToExplorerText !== false;
      const textColorRule = applyTextColor ? `color: ${rule.customTextColorEnabled ? rule.customTextColor : "var(--text-normal)"} !important;` : "";
      const textOnlyColorRule = applyTextColor ? `color: ${rule.customTextColorEnabled ? rule.customTextColor : rule.color} !important;` : "";
      if (settings.fileExplorerStyle === "background") {
        css += `
          .nav-folder-title[data-path="${rule.folderPath}"],
          .nav-folder-title[data-path^="${rule.folderPath}/"] {
            background-color: rgba(${r}, ${g}, ${b}, 0.25) !important;
            ${textColorRule}
            border-radius: 5px !important;
          }
          .nav-folder-title[data-path="${rule.folderPath}"]:hover,
          .nav-folder-title[data-path^="${rule.folderPath}/"]:hover {
            background-color: rgba(${r}, ${g}, ${b}, 0.45) !important;
          }
          .nav-folder-title[data-path="${rule.folderPath}"] .nav-folder-icon,
          .nav-folder-title[data-path^="${rule.folderPath}/"] .nav-folder-icon {
            ${textColorRule}
          }
        `;
      } else {
        if (applyTextColor) {
          css += `
            .nav-folder-title[data-path="${rule.folderPath}"],
            .nav-folder-title[data-path^="${rule.folderPath}/"] {
              ${textOnlyColorRule}
            }
            .nav-folder-title[data-path="${rule.folderPath}"] .nav-folder-icon,
            .nav-folder-title[data-path^="${rule.folderPath}/"] .nav-folder-icon {
              ${textOnlyColorRule}
            }
          `;
        }
      }
    }
  });
  if (settings.pinnedTabStyle === "dot") {
    css += `
      .workspace-tab-header.is-pinned[data-tabprism-rule] .workspace-tab-header-status-container,
      .workspace-tab-header.mod-pinned[data-tabprism-rule] .workspace-tab-header-status-container {
        display: flex;
        align-items: center;
        justify-content: center;
      }
      .workspace-tab-header.is-pinned[data-tabprism-rule] .workspace-tab-header-status-container svg,
      .workspace-tab-header.mod-pinned[data-tabprism-rule] .workspace-tab-header-status-container svg {
        display: none !important;
      }
      .workspace-tab-header.is-pinned[data-tabprism-rule] .workspace-tab-header-status-container::after,
      .workspace-tab-header.mod-pinned[data-tabprism-rule] .workspace-tab-header-status-container::after {
        content: '';
        display: block;
        width: 8px;
        height: 8px;
        border-radius: 50%;
        background-color: var(--tab-folder-accent) !important;
      }
    `;
  } else if (settings.pinnedTabStyle === "underline") {
    css += `
      .workspace-tab-header.is-pinned[data-tabprism-rule] .workspace-tab-header-inner,
      .workspace-tab-header.mod-pinned[data-tabprism-rule] .workspace-tab-header-inner {
        border-bottom: 3px solid var(--tab-folder-accent) !important;
      }
    `;
  }
  return css;
}

// src/tabManager.ts
function matchesRule(filePath, folderPath) {
  if (!filePath || typeof filePath !== "string")
    return false;
  if (!folderPath || typeof folderPath !== "string")
    return false;
  const normalizedFile = filePath.replace(/\\/g, "/").replace(/^\/+/, "");
  const normalizedFolder = folderPath.replace(/\\/g, "/").replace(/^\/+|\/+$/g, "");
  return normalizedFile === normalizedFolder || normalizedFile.startsWith(normalizedFolder + "/");
}
function updateTabs(app, settings, sortedRules) {
  app.workspace.iterateAllLeaves((leaf) => {
    var _a, _b, _c;
    const tabHeader = leaf.tabHeaderEl;
    if (!tabHeader)
      return;
    const viewState = leaf.getViewState();
    const filePath = ((_b = (_a = leaf.view) == null ? void 0 : _a.file) == null ? void 0 : _b.path) || ((_c = viewState == null ? void 0 : viewState.state) == null ? void 0 : _c.file);
    tabHeader.removeAttribute("data-tabprism-rule");
    tabHeader.removeAttribute("data-style-bg");
    tabHeader.removeAttribute("data-style-border");
    tabHeader.removeAttribute("data-style-text");
    tabHeader.removeAttribute("data-style-icons");
    if (!filePath || typeof filePath !== "string")
      return;
    for (const rule of sortedRules) {
      if (rule.enabled === false)
        continue;
      if (matchesRule(filePath, rule.folderPath)) {
        tabHeader.setAttribute("data-tabprism-rule", rule.id);
        if (rule.applyToBackground)
          tabHeader.setAttribute("data-style-bg", "true");
        if (rule.applyToBorder)
          tabHeader.setAttribute("data-style-border", "true");
        if (rule.applyToText)
          tabHeader.setAttribute("data-style-text", "true");
        if (rule.applyToIcons)
          tabHeader.setAttribute("data-style-icons", "true");
        break;
      }
    }
  });
}
function updateFileExplorer(app, sortedRules) {
}

// src/settingsTab.ts
var import_obsidian2 = require("obsidian");

// src/folderSuggest.ts
var import_obsidian = require("obsidian");
var FolderSuggest = class extends import_obsidian.AbstractInputSuggest {
  constructor(app, textInputEl) {
    super(app, textInputEl);
    this.textInputEl = textInputEl;
  }
  getSuggestions(inputStr) {
    const folders = this.app.vault.getAllLoadedFiles().filter((f) => f instanceof import_obsidian.TFolder);
    const lowerCaseInputStr = inputStr.toLowerCase();
    return folders.filter((folder) => folder.path.toLowerCase().includes(lowerCaseInputStr));
  }
  renderSuggestion(folder, el) {
    el.setText(folder.path);
  }
  selectSuggestion(folder) {
    this.textInputEl.value = folder.path;
    this.textInputEl.trigger("input");
    this.close();
  }
};

// src/settingsTab.ts
var TabPrismSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Sync file explorer").setDesc("Mirror tab colors onto corresponding sidebar folder titles and icons.").addToggle((toggle) => toggle.setValue(this.plugin.settings.syncFileExplorer).onChange(async (value) => {
      this.plugin.settings.syncFileExplorer = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("File explorer style").setDesc("How the colors should apply to file explorer folders.").addDropdown((dropdown) => dropdown.addOption("text", "Text only").addOption("background", "Background fill").setValue(this.plugin.settings.fileExplorerStyle || "text").onChange(async (value) => {
      this.plugin.settings.fileExplorerStyle = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Pinned tab display").setDesc("How pinned tabs should be indicated.").addDropdown((dropdown) => dropdown.addOption("full", "Full Fill").addOption("dot", "Accent Dot").addOption("underline", "Underline Indicator").addOption("none", "None").setValue(this.plugin.settings.pinnedTabStyle).onChange(async (value) => {
      this.plugin.settings.pinnedTabStyle = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Folder Rules" });
    new import_obsidian2.Setting(containerEl).setName("Add new rule").setDesc("Create a new color rule for a folder path.").addButton((button) => button.setButtonText("Add Rule").setCta().onClick(async () => {
      this.plugin.settings.rules.push({
        id: crypto.randomUUID(),
        folderPath: "",
        color: COLOR_PRESETS[0].hex,
        activeOpacity: 0.28,
        inactiveOpacity: 0.16,
        applyToBackground: true,
        applyToBorder: true,
        applyToText: true,
        applyToIcons: true,
        applyToExplorerText: true,
        enabled: true,
        isCollapsed: false,
        customTextColorEnabled: false,
        customTextColor: "#ffffff"
      });
      await this.plugin.saveSettings();
      this.display();
    }));
    this.plugin.settings.rules.forEach((rule, index) => {
      this.renderRule(containerEl, rule, index);
    });
    containerEl.createEl("h3", { text: "Import / Export" });
    const importExportSetting = new import_obsidian2.Setting(containerEl).setName("Import or export settings").setDesc("Copy your settings to clipboard or paste to import.").addButton((btn) => btn.setButtonText("Export").onClick(() => {
      navigator.clipboard.writeText(JSON.stringify(this.plugin.settings, null, 2));
      new import_obsidian2.Notice("TabPrism settings copied to clipboard.");
    }));
    importExportSetting.addButton((btn) => btn.setButtonText("Import").onClick(() => {
      new ImportModal(this.app, this.plugin, () => this.display()).open();
    }));
  }
  renderRule(containerEl, rule, index) {
    if (rule.enabled === void 0)
      rule.enabled = true;
    if (rule.isCollapsed === void 0)
      rule.isCollapsed = false;
    if (rule.applyToExplorerText === void 0)
      rule.applyToExplorerText = true;
    if (rule.customTextColorEnabled === void 0)
      rule.customTextColorEnabled = false;
    if (rule.customTextColor === void 0)
      rule.customTextColor = "#ffffff";
    const ruleCard = containerEl.createDiv("tabprism-rule-card");
    ruleCard.style.border = "1px solid var(--background-modifier-border)";
    ruleCard.style.marginBottom = "10px";
    ruleCard.style.borderRadius = "5px";
    ruleCard.style.overflow = "hidden";
    const headerDiv = ruleCard.createDiv("tabprism-rule-header");
    headerDiv.style.padding = "10px";
    headerDiv.style.backgroundColor = "var(--background-secondary)";
    headerDiv.style.cursor = "pointer";
    headerDiv.style.display = "flex";
    headerDiv.style.alignItems = "center";
    headerDiv.style.justifyContent = "space-between";
    const headerLeft = headerDiv.createDiv();
    headerLeft.style.display = "flex";
    headerLeft.style.alignItems = "center";
    headerLeft.style.gap = "10px";
    const toggleEnabled = document.createElement("input");
    toggleEnabled.type = "checkbox";
    toggleEnabled.checked = rule.enabled;
    toggleEnabled.title = "Enable/Disable Rule";
    toggleEnabled.onclick = async (e) => {
      e.stopPropagation();
      rule.enabled = toggleEnabled.checked;
      await this.plugin.saveSettings();
    };
    headerLeft.appendChild(toggleEnabled);
    const titleEl = headerLeft.createSpan();
    titleEl.setText(rule.folderPath || `Rule ${index + 1} (Unset)`);
    titleEl.style.fontWeight = "bold";
    const headerRight = headerDiv.createDiv();
    headerRight.style.display = "flex";
    headerRight.style.alignItems = "center";
    headerRight.style.gap = "10px";
    const collapseIcon = headerRight.createSpan();
    collapseIcon.setText(rule.isCollapsed ? "\u25C0" : "\u25BC");
    collapseIcon.style.fontSize = "0.8em";
    collapseIcon.style.color = "var(--text-muted)";
    const contentDiv = ruleCard.createDiv("tabprism-rule-content");
    contentDiv.style.padding = "10px";
    contentDiv.style.display = rule.isCollapsed ? "none" : "block";
    headerDiv.onclick = async () => {
      rule.isCollapsed = !rule.isCollapsed;
      collapseIcon.setText(rule.isCollapsed ? "\u25C0" : "\u25BC");
      contentDiv.style.display = rule.isCollapsed ? "none" : "block";
      await this.plugin.saveSettings();
    };
    new import_obsidian2.Setting(contentDiv).setName(`Folder Path`).addSearch((search) => {
      new FolderSuggest(this.app, search.inputEl);
      search.setPlaceholder("Folder path").setValue(rule.folderPath).onChange(async (value) => {
        rule.folderPath = value;
        titleEl.setText(value || `Rule ${index + 1} (Unset)`);
        await this.plugin.saveSettings();
      });
    }).addButton((btn) => btn.setIcon("trash").setTooltip("Delete rule").onClick(async () => {
      this.plugin.settings.rules.splice(index, 1);
      await this.plugin.saveSettings();
      this.display();
    }));
    const colorSetting = new import_obsidian2.Setting(contentDiv).setName("Color");
    colorSetting.addColorPicker((color) => color.setValue(rule.color).onChange(async (value) => {
      rule.color = value;
      if (hexInput)
        hexInput.setValue(value);
      await this.plugin.saveSettings();
    }));
    let hexInput;
    colorSetting.addText((text) => {
      hexInput = text;
      text.setPlaceholder("#000000").setValue(rule.color).onChange(async (value) => {
        rule.color = value;
        if (/^#[0-9A-F]{6}$/i.test(value) || /^#[0-9A-F]{3}$/i.test(value)) {
          const picker = colorSetting.components[0].colorPickerEl;
          if (picker)
            picker.value = value;
        }
        await this.plugin.saveSettings();
      });
    });
    const presetContainer = colorSetting.controlEl.createDiv("tabprism-presets");
    presetContainer.style.display = "flex";
    presetContainer.style.gap = "5px";
    presetContainer.style.marginLeft = "10px";
    COLOR_PRESETS.forEach((preset) => {
      const swatch = presetContainer.createDiv();
      swatch.style.width = "20px";
      swatch.style.height = "20px";
      swatch.style.borderRadius = "50%";
      swatch.style.backgroundColor = preset.hex;
      swatch.style.cursor = "pointer";
      swatch.title = preset.name;
      swatch.onclick = async () => {
        rule.color = preset.hex;
        if (hexInput)
          hexInput.setValue(preset.hex);
        const picker = colorSetting.components[0].colorPickerEl;
        if (picker)
          picker.value = preset.hex;
        await this.plugin.saveSettings();
      };
    });
    new import_obsidian2.Setting(contentDiv).setName("Active Opacity").addSlider((slider) => slider.setLimits(0, 1, 0.02).setValue(rule.activeOpacity).setDynamicTooltip().onChange(async (value) => {
      rule.activeOpacity = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(contentDiv).setName("Inactive Opacity").addSlider((slider) => slider.setLimits(0, 1, 0.02).setValue(rule.inactiveOpacity).setDynamicTooltip().onChange(async (value) => {
      rule.inactiveOpacity = value;
      await this.plugin.saveSettings();
    }));
    const targetsSetting = new import_obsidian2.Setting(contentDiv).setName("Target Elements");
    targetsSetting.controlEl.empty();
    targetsSetting.controlEl.style.display = "flex";
    targetsSetting.controlEl.style.gap = "15px";
    targetsSetting.controlEl.style.flexWrap = "wrap";
    targetsSetting.controlEl.style.justifyContent = "flex-end";
    const createLabeledToggle = (label, value, onChange) => {
      const container = targetsSetting.controlEl.createDiv();
      container.style.display = "flex";
      container.style.alignItems = "center";
      container.style.gap = "5px";
      const toggle = new import_obsidian2.ToggleComponent(container).setValue(value).onChange(onChange);
      const span = container.createSpan();
      span.setText(label);
    };
    createLabeledToggle("Background", rule.applyToBackground, async (v) => {
      rule.applyToBackground = v;
      await this.plugin.saveSettings();
    });
    createLabeledToggle("Border", rule.applyToBorder, async (v) => {
      rule.applyToBorder = v;
      await this.plugin.saveSettings();
    });
    createLabeledToggle("Text", rule.applyToText, async (v) => {
      rule.applyToText = v;
      await this.plugin.saveSettings();
    });
    createLabeledToggle("Icons", rule.applyToIcons, async (v) => {
      rule.applyToIcons = v;
      await this.plugin.saveSettings();
    });
    const customTextSetting = new import_obsidian2.Setting(contentDiv).setName("Custom Text Color").setDesc("Override the text/icon color independently from the background accent.").addToggle((toggle) => toggle.setValue(rule.customTextColorEnabled).onChange(async (value) => {
      rule.customTextColorEnabled = value;
      customColorSetting.settingEl.style.display = value ? "flex" : "none";
      await this.plugin.saveSettings();
    }));
    const explorerTextSetting = new import_obsidian2.Setting(contentDiv).setName("Apply to File Explorer Text").setDesc("Apply color tinting to the text of the folder title in the file explorer.").addToggle((toggle) => toggle.setValue(rule.applyToExplorerText !== false).onChange(async (value) => {
      rule.applyToExplorerText = value;
      await this.plugin.saveSettings();
    }));
    const customColorSetting = new import_obsidian2.Setting(contentDiv).setName("Text Color").addColorPicker((color) => color.setValue(rule.customTextColor).onChange(async (value) => {
      rule.customTextColor = value;
      await this.plugin.saveSettings();
    }));
    customColorSetting.settingEl.style.display = rule.customTextColorEnabled ? "flex" : "none";
  }
};
var ImportModal = class extends import_obsidian2.Modal {
  constructor(app, plugin, onImport) {
    super(app);
    this.textValue = "";
    this.plugin = plugin;
    this.onImport = onImport;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Import Settings" });
    new import_obsidian2.Setting(contentEl).setName("JSON Data").addTextArea((text) => {
      text.setPlaceholder("Paste settings JSON here...").onChange((value) => {
        this.textValue = value;
      });
      text.inputEl.setAttribute("rows", "10");
      text.inputEl.style.width = "100%";
    });
    new import_obsidian2.Setting(contentEl).addButton((btn) => btn.setButtonText("Import").setCta().onClick(async () => {
      try {
        const parsed = JSON.parse(this.textValue);
        if (parsed && typeof parsed === "object") {
          this.plugin.settings = Object.assign({}, this.plugin.settings, parsed);
          await this.plugin.saveSettings();
          new import_obsidian2.Notice("Settings imported successfully.");
          this.onImport();
          this.close();
        }
      } catch (e) {
        new import_obsidian2.Notice("Invalid JSON. Import failed.");
        console.error("Import error:", e);
      }
    }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/main.ts
var TabPrismPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new TabPrismSettingTab(this.app, this));
    this.styleEl = document.createElement("style");
    this.styleEl.id = "tabprism-dynamic-styles";
    document.head.appendChild(this.styleEl);
    this.applySettings();
    this.app.workspace.onLayoutReady(() => {
      this.refreshAll();
    });
    this.registerEvent(this.app.workspace.on("layout-change", () => this.refreshAll()));
    this.registerEvent(this.app.workspace.on("active-leaf-change", () => this.refreshAll()));
    this.registerEvent(this.app.workspace.on("file-open", () => this.refreshAll()));
    this.registerEvent(this.app.vault.on("rename", () => this.refreshAll()));
    this.registerEvent(this.app.vault.on("delete", () => this.refreshAll()));
  }
  onunload() {
    if (this.styleEl && this.styleEl.parentNode) {
      this.styleEl.parentNode.removeChild(this.styleEl);
    }
    this.app.workspace.iterateAllLeaves((leaf) => {
      const tabHeader = leaf.tabHeaderEl;
      if (tabHeader) {
        tabHeader.removeAttribute("data-tabprism-rule");
        tabHeader.removeAttribute("data-style-bg");
        tabHeader.removeAttribute("data-style-border");
        tabHeader.removeAttribute("data-style-text");
        tabHeader.removeAttribute("data-style-icons");
      }
    });
    document.querySelectorAll(".nav-folder[data-tabprism-rule]").forEach((el) => {
      el.removeAttribute("data-tabprism-rule");
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.applySettings();
  }
  applySettings() {
    this.styleEl.textContent = generateDynamicCSS(this.settings);
    this.refreshAll();
  }
  refreshAll() {
    const sortedRules = [...this.settings.rules].sort((a, b) => {
      const depthDiff = b.folderPath.split("/").length - a.folderPath.split("/").length;
      if (depthDiff !== 0)
        return depthDiff;
      return b.folderPath.length - a.folderPath.length;
    });
    updateTabs(this.app, this.settings, sortedRules);
    if (this.settings.syncFileExplorer) {
      updateFileExplorer(this.app, sortedRules);
    } else {
      document.querySelectorAll(".nav-folder[data-tabprism-rule]").forEach((el) => {
        el.removeAttribute("data-tabprism-rule");
      });
    }
  }
};
